version: '3.8'

services:
  nodejs:
    build:
      context: ./node
      dockerfile: nodejsapp.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: superapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
